name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install PlatformIO
      run: |
        pip install wheel
        python -m pip install --upgrade pip setuputils
        pip --version
        pip install -U platformio
        pip platformio --version
    - name: build
      run: |
        pip platformio run
